### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by ahmedelgabri** [joshhartigan/vim-reddit#3]
When I try to open some reddits, I get this error. For example I had this with `vim` and `soccer` reddits

```
Error detected while processing function provider#python#Call:
line   18:
HTTPError()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
HTTPError: HTTP Error 429: Too Many Requests

Press ENTER or type command to continue
```

**Comment by bag-man** [comment]
I think that is because you included the `/r/` in the sub-reddit name. Try just `:Reddit askreddit` for example.

**Comment by mdxprograms** [comment]
I'm getting the same with just `webdev` as the sub entered

**Comment by mdxprograms** [comment]
Strange it worked after the third time entering it...
