### ISSUE TITLE
Not working in NeoVim

### ISSUE THREAD

**Issue by JD557** [joshhartigan/vim-reddit#6]
Trying to open a subreddit in NeoVim 0.1.7 does not work:

```
Error detected while processing function provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/joao/.vim/bundle/vim-reddit/plugin/vimreddit.py", line 52, in vim_reddit
    items = json.loads(urllib2.urlopen(redditurl(sub)).read())
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_respons
e
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib
```

The plugin works fine on vim 8.0.123 (with the same .vimrc and plugins).

Also, I can run `ryanss/vim-hackernews` just fine on NeoVim.

**Comment by JD557** [comment]
Turns out that this is not related to NeoVim, but with #3 

I'll send a PR to fix this.
